import { BouquetGift, DailyNote, FlowerItem, LoveReason, MemoryPhoto, OpenWhenLetter } from '../types';

export const INITIAL_COUPLE = {
  herName: 'My Girl 🎀',
  hisName: 'Aymaan',
  relationshipStartDate: '2023-09-20',
  herNickname: 'My Cutie Princess',
  soundEnabled: true,
  ambientMusicPlaying: false,
};

export const FLOWER_CATALOG: FlowerItem[] = [
  {
    id: 'pink-tulip',
    name: 'Pink Tulip',
    koreanName: '분홍 튤립',
    meaning: 'Deep caring, gentle affection & forever attachment',
    color: '#FF70A6',
    svgType: 'tulip',
  },
  {
    id: 'red-rose',
    name: 'Classic Velvet Rose',
    koreanName: '장미',
    meaning: 'Unconditional love, eternal passion & devotion',
    color: '#E63946',
    svgType: 'rose',
  },
  {
    id: 'cherry-blossom',
    name: 'Sakura Blossom',
    koreanName: '벚꽃',
    meaning: 'Gentle beauty, sweet renewal & poetic romance',
    color: '#FFB7B2',
    svgType: 'cherry',
  },
  {
    id: 'peony-bloom',
    name: 'Pastel Peony',
    koreanName: '작약',
    meaning: 'Happy union, prosperity & pure romance',
    color: '#F48498',
    svgType: 'peony',
  },
  {
    id: 'daisy-sun',
    name: 'Sweet White Daisy',
    koreanName: '데이지',
    meaning: 'Purity, innocence & the brightest smile in my world',
    color: '#FFF176',
    svgType: 'daisy',
  },
  {
    id: 'sunflower-warm',
    name: 'Golden Sunflower',
    koreanName: '해바라기',
    meaning: 'Adoration, loyalty & you are my sunshine on cloudy days',
    color: '#FFB703',
    svgType: 'sunflower',
  },
  {
    id: 'babys-breath',
    name: "Baby's Breath",
    koreanName: '안개꽃',
    meaning: 'Everlasting sincerity & endless starry love',
    color: '#E0AAFF',
    svgType: 'babysbreath',
  },
  {
    id: 'strawberry-flower',
    name: 'Strawberry Blossom',
    koreanName: '딸기꽃',
    meaning: 'Sweetest joy, warmth & delicious memories',
    color: '#FF4D6D',
    svgType: 'strawberry',
  },
  {
    id: 'kitty-bow-flower',
    name: 'Hello Kitty Bow Bloom',
    koreanName: '키티 리본꽃',
    meaning: 'Cute magic, forever tied together & pure sweetness',
    color: '#FF3366',
    svgType: 'kittybow',
  },
];

export const WRAPPING_STYLES = [
  { id: 'pink-gingham', name: 'Pastel Pink Gingham', color: '#FFE0E9', patternClass: 'bg-gingham-pink', border: '#FF99B8' },
  { id: 'lavender-dots', name: 'Lilac Dream Polka', color: '#F3E8FF', patternClass: 'bg-polka-pink', border: '#D8B4FE' },
  { id: 'cream-silk', name: 'Strawberry Cream Silk', color: '#FFF8F0', patternClass: 'bg-[#FFF8F0]', border: '#FFD7BA' },
  { id: 'strawberry-delight', name: 'Strawberry Blush', color: '#FFE4E6', patternClass: 'bg-[#FFE4E6]', border: '#FDA4AF' },
  { id: 'classic-kraft', name: 'Warm Kraft & Red Bow', color: '#F8EDE3', patternClass: 'bg-[#F8EDE3]', border: '#DDB892' },
];

export const INITIAL_BOUQUETS: BouquetGift[] = [
  {
    id: 'b-1',
    title: 'A Bloom of Forever Love 🎀',
    recipientName: 'My Girl 🎀',
    senderName: 'Aymaan',
    date: 'August 16, 2026',
    wrappingStyle: 'pink-gingham',
    ribbonColor: '#FF3366',
    flowers: [
      { flowerId: 'pink-tulip', count: 3, name: 'Pink Tulip', color: '#FF70A6', meaning: 'Deep caring & affection' },
      { flowerId: 'red-rose', count: 2, name: 'Classic Rose', color: '#E63946', meaning: 'Eternal devotion' },
      { flowerId: 'kitty-bow-flower', count: 2, name: 'Kitty Bow Bloom', color: '#FF3366', meaning: 'Forever tied together' },
      { flowerId: 'babys-breath', count: 4, name: "Baby's Breath", color: '#E0AAFF', meaning: 'Everlasting starry love' },
    ],
    note: 'To the girl who makes my ordinary days feel like soft pink fairytale magic. I am endlessly grateful and so overwhelmingly lucky to call you mine. Happy every single day with you! 💖',
    greetingCardTheme: 'kitty-classic',
  },
];

export const LOVE_REASONS: LoveReason[] = [
  {
    id: 1,
    title: 'The Way Your Eyes Crinkle When You Laugh',
    description: 'Whenever you genuinely giggle or smile, your whole face lights up. It instantly erases all my worries and makes the entire room brighter.',
    tag: 'Heartwarming',
    icon: '✨',
  },
  {
    id: 2,
    title: 'How Safe and Warm I Feel Beside You',
    description: 'No matter how chaotic or loud the world gets, the moment I hear your voice or hold your hand, I am instantly at home and completely at peace.',
    tag: 'Comfort',
    icon: '🏡',
  },
  {
    id: 3,
    title: 'Your Boundless Kindness and Gentle Heart',
    description: 'You care so deeply about the people around you and notice the little things no one else does. Your empathy is one of the many reasons I admire you endlessly.',
    tag: 'Admiration',
    icon: '🌸',
  },
  {
    id: 4,
    title: 'How You Make Even Boring Groceries Magical',
    description: 'Even just walking down random supermarket aisles or sitting in the car with you turns into the most fun adventure filled with laughter and cute jokes.',
    tag: 'Joy',
    icon: '🛒',
  },
  {
    id: 5,
    title: 'Your Adorable Pouts and Cute Expressions',
    description: 'Every little facial expression you make is cuter than anything Sanrio could ever design. I catch myself just staring at you and smiling like a goofball.',
    tag: 'Cutie',
    icon: '🎀',
  },
  {
    id: 6,
    title: 'You Believe In Me Even When I Doubt Myself',
    description: 'Having you as my biggest cheerleader gives me the strength to overcome anything. You see the best in me and inspire me to be a better person every day.',
    tag: 'Gratitude',
    icon: '🌟',
  },
  {
    id: 7,
    title: 'The Sweet Way You Care For Me',
    description: 'Asking if I ate, making sure I am resting, or sending me sweet check-ins—your love is woven into every small gesture and I cherish it with all my soul.',
    tag: 'Affection',
    icon: '💌',
  },
  {
    id: 8,
    title: 'Our Matching Humor & Secret Inside Jokes',
    description: 'We can just exchange a single look across a crowded room and burst into laughter because we both know exactly what the other is thinking.',
    tag: 'Soulmate',
    icon: '🤭',
  },
  {
    id: 9,
    title: 'How Incredibly Lucky I Am That You Chose Me',
    description: 'Out of all 8 billion people on this planet, I got to hold the hand of the most gorgeous, sweet, smart, and loving girl. I will never take that for granted.',
    tag: 'Blessed',
    icon: '🍀',
  },
  {
    id: 10,
    title: 'Building Our Dreams and Future Together',
    description: 'Every plan we make, every future trip we talk about, and every dream we whisper makes me so excited for all the years we get to spend together.',
    tag: 'Forever',
    icon: '💍',
  },
  {
    id: 11,
    title: 'The Scent of Your Hugs',
    description: 'Your hugs are the coziest shelter in the universe. Everything smells like sweet vanilla, comfort, and unconditional love.',
    tag: 'Cozy',
    icon: '🧸',
  },
  {
    id: 12,
    title: 'Simply Because You Are YOU',
    description: 'Flawed, perfect, silly, sleepy, sassy, sweet—every single piece of who you are is what I fell head over heels for, and what I will love forever.',
    tag: 'Unconditional',
    icon: '❤️',
  },
];

export const INITIAL_OPEN_WHEN: OpenWhenLetter[] = [
  {
    id: 'ow-1',
    openWhen: 'Open when you miss me terribly...',
    teaser: 'A little reminder that my heart is always right beside yours',
    icon: '💌',
    sealedColor: '#FF6B8B',
    content: `My dearest love,\n\nIf you are reading this, take a deep breath and close your eyes for three seconds. Imagine my arms wrapping gently around you, pulling you in close so you can hear my heartbeat.\n\nDistance or time cannot change how completely head-over-heels I am for you. Whenever you miss me, look at the stars or touch your chest—I am thinking of you right at this very moment, smiling because I have the prettiest angel in the world.\n\nI will text/call you as soon as I can. Until then, remember that I love you more than words can ever describe! 💖`,
  },
  {
    id: 'ow-2',
    openWhen: "Open when you've had a tough, exhausting day...",
    teaser: 'You are so strong, but right now it is time to rest',
    icon: '🧸',
    sealedColor: '#9D4EDD',
    content: `My sweet girl,\n\nI know today was heavy and your energy might feel completely drained. I wish I was right there to tuck you into a fluffy blanket, make you a warm cup of cocoa, give you a gentle forehead kiss, and listen to everything.\n\nListen to me carefully: You did so well today. Even if things did not go as planned, you are resilient, brilliant, and doing your absolute best. Let go of today's burdens—tomorrow is a brand new page, and I will be right by your side cheering you on.\n\nDrink some water, put on your comfiest pajamas, and rest your sweet head. I love you so much. 🌸`,
  },
  {
    id: 'ow-3',
    openWhen: 'Open when you need a reminder of how beautiful you are...',
    teaser: 'The honest truth from the boy who adores you most',
    icon: '✨',
    sealedColor: '#FF9E00',
    content: `My gorgeous princess,\n\nWhether your hair is styled or in a messy sleepy bun, whether you are in your fanciest dress or an oversized hoodie, you are breathtaking.\n\nIt is not just your gorgeous eyes, your cute nose, or that radiant smile—it is the kindness radiating from your soul. You have this magical grace that effortlessly captures everyone's heart, especially mine.\n\nNever doubt your beauty for a single fraction of a second. To me, you are the most stunning girl to ever walk this earth! 🎀`,
  },
  {
    id: 'ow-4',
    openWhen: "Open when you can't fall asleep at night...",
    teaser: 'A soft bedtime lullaby of thoughts for your sweet dreams',
    icon: '🌙',
    sealedColor: '#3A86FF',
    content: `My sleepy angel,\n\nAre your thoughts spinning in circles? Let's count our favorite happy memories together instead.\n\nThink about our favorite laughs, the softest moments we held hands, the sweet dates we went on, and all the warm sunny days waiting for us. Imagine us cuddled up under a cozy cloud, safe and warm.\n\nTurn off your phone, close those pretty eyes, and let all the tension melt away. I'll meet you in dreamland! Goodnight, my forever love. 💤✨`,
  },
  {
    id: 'ow-5',
    openWhen: 'Open when you need a burst of pure happiness...',
    teaser: 'A quick joke, cute facts, and a mountain of affection',
    icon: '🍓',
    sealedColor: '#FF006E',
    content: `Hello my little strawberry sunshine!\n\nHere is your official emergency joy delivery:\n1. You are cute.\n2. You are smart.\n3. Hello Kitty approves this message.\n4. Aymaan loves you 10,000,000%!\n\nDid you know that otters hold hands when they sleep so they don't drift apart? That is literally us. Put a smile on that cute face because you are the happiest blessing in my life! 🥰`,
  },
];

export const INITIAL_DAILY_NOTES: DailyNote[] = [
  {
    id: 'n-1',
    date: 'Today',
    title: 'Just a reminder that you are my favorite person',
    content: 'Woke up thinking about how much lighter and happier my life became the moment you walked into it. You make every ordinary moment feel special. Hope your day is filled with sweet smiles! 🎀',
    author: 'Aymaan',
    stationery: 'pink-gingham',
    mood: 'loved',
    isPinned: true,
  },
  {
    id: 'n-2',
    date: 'Yesterday',
    title: 'Thank you for your warm smile',
    content: 'That cute little laugh you did when we were talking made my whole afternoon. I saved that sound in my mental treasure chest. You are my sunshine! ☀️',
    author: 'Aymaan',
    stationery: 'strawberry',
    mood: 'grateful',
  },
  {
    id: 'n-3',
    date: 'August 14, 2026',
    title: 'Our late night conversation 🌙',
    content: 'Talking to you before sleeping is the sweetest part of my day. I could listen to you talk about your day, your dreams, and your favorite things forever.',
    author: 'Aymaan',
    stationery: 'lavender',
    mood: 'sweet',
  },
];

export const INITIAL_MEMORIES: MemoryPhoto[] = [
  {
    id: 'm-1',
    title: 'Our Cozy Cafe Date ☕🍰',
    date: 'October 14, 2024',
    location: 'Sweet Petal Bakery & Cafe',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    caption: 'Sharing sweet strawberry shortcakes and laughing until our cheeks hurt.',
    backNote: 'This was the day you wiped cream off your nose and made the cutest pout. I remember sitting across from you and thinking: "I am going to love this girl forever."',
    category: 'dates',
    isFavorite: true,
    stickers: ['🎀', '☕', '🍓'],
  },
  {
    id: 'm-2',
    title: 'Sunset Walks Hand in Hand 🌅',
    date: 'December 24, 2024',
    location: 'Golden Shoreline Promenade',
    imageUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80',
    caption: 'Watching the pink and lavender sky reflect in your eyes.',
    backNote: 'The breeze was chilly, so you tucked your cold hand directly into my coat pocket. My heart was pounding so fast you probably heard it.',
    category: 'cozy',
    isFavorite: true,
    stickers: ['✨', '💖', '🌊'],
  },
  {
    id: 'm-3',
    title: 'Picnic Under the Cherry Blossoms 🌸',
    date: 'April 8, 2025',
    location: 'Botanical Blossom Gardens',
    imageUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80',
    caption: 'A blanket, sweet treats, and pink petals falling softly around us.',
    backNote: 'A flower petal landed right in your hair and you looked just like a fairy. I never wanted that afternoon to end.',
    category: 'trips',
    stickers: ['🌸', '🧺', '✨'],
  },
  {
    id: 'm-4',
    title: 'Winning That Giant Hello Kitty Plushie 🧸',
    date: 'July 19, 2025',
    location: 'Summer Carnival Lights',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    caption: 'Your happy scream when we finally won the arcade game!',
    backNote: 'I spent way too many tokens trying to win it for you, but seeing your face light up and you hugging the plushie made it worth 1000x over.',
    category: 'milestones',
    isFavorite: true,
    stickers: ['🎀', '🎡', '🌟'],
  },
  {
    id: 'm-5',
    title: 'Rainy Day Studio Movie Marathon 🍿',
    date: 'November 2, 2025',
    location: 'Our Cozy Blanket Fort',
    imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    caption: 'Pajamas, fairy lights, warm tea, and sharing the fluffiest duvet.',
    backNote: 'You fell asleep halfway through the movie with your head resting on my shoulder. I barely moved a muscle because I did not want to wake you up.',
    category: 'cozy',
    stickers: ['🍿', '🌧️', '🧸'],
  },
];

export const DAILY_LOVE_FORTUNES = [
  '🎀 Hello Kitty Fortune: Aymaan thinks you are 1000% cuter today than yesterday!',
  '💖 Sweet Secret: Looking at your smile instantly makes any cloudy day 100x brighter.',
  '🍓 Love Cookie: You are the strawberry jam to my toast, sweet and irreplaceable.',
  '✨ Star Whisper: You are Aymaan’s favorite thought in the morning and sweet dream at night.',
  '🌸 Angel Note: Thank you for being the most loving, wonderful partner in the entire universe.',
  '💌 Love Metric: Affection levels are currently off the charts (Infinite/10)!',
  '🎀 Bow Blessing: May your day be filled with warm smiles, cute drinks, and soft moments.',
];
